import Head from "next/head";
import { Sidebar } from "@/components";

export default function Home() {
  return (
    <div className="Home bg-black min-h-screen flex">
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Sidebar />
    </div>
  );
}
